spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration



spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false   # ⭐ THIS IS THE MISSING PIECE

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

product:
  service:
    url: http://localhost:9090
