server:
  port: 8081

spring:
  application:
    name: order-service
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

product:
  service:
    url: http://localhost:9090
